services:
  frontend:
    environment:
      DOMAIN: ${DOMAIN}
    ports:
      - "443:443"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/templates/default.conf.template:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
